CREATE TABLE IF NOT EXISTS `clients` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `client_code` VARCHAR(50) NOT NULL UNIQUE,
    `client_type` ENUM('individual', 'company') NOT NULL DEFAULT 'individual',
    `name` VARCHAR(191) NOT NULL,
    `contact_person` VARCHAR(150) NULL DEFAULT NULL,
    `email` VARCHAR(191) NOT NULL UNIQUE,
    `mobile` VARCHAR(20) NOT NULL UNIQUE,
    `alt_mobile` VARCHAR(20) NULL DEFAULT NULL,
    `gst_no` VARCHAR(15) NULL DEFAULT NULL UNIQUE,
    `pan_no` VARCHAR(10) NULL DEFAULT NULL,
    `industry` VARCHAR(100) NULL DEFAULT NULL,
    `company_size` VARCHAR(50) NULL DEFAULT NULL,
    `website` VARCHAR(255) NULL DEFAULT NULL,
    `address_line1` VARCHAR(255) NULL DEFAULT NULL,
    `address_line2` VARCHAR(255) NULL DEFAULT NULL,
    `city` VARCHAR(100) NULL DEFAULT NULL,
    `state` VARCHAR(100) NULL DEFAULT NULL,
    `pincode` VARCHAR(20) NULL DEFAULT NULL,
    `country` VARCHAR(100) NOT NULL DEFAULT 'India',
    `lead_source` VARCHAR(100) NULL DEFAULT NULL,
    `assigned_to` BIGINT UNSIGNED NULL DEFAULT NULL,
    `status` ENUM('new', 'active', 'inactive') NOT NULL DEFAULT 'new',
    `tags` TEXT NULL DEFAULT NULL,
    `notes` TEXT NULL DEFAULT NULL,
    `consent_given` TINYINT(1) NOT NULL DEFAULT 0,
    `consent_at` DATETIME NULL DEFAULT NULL,
    `created_by` BIGINT UNSIGNED NULL DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL DEFAULT NULL,
    CONSTRAINT `fk_clients_assigned_to` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_clients_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    INDEX `idx_clients_status` (`status`),
    INDEX `idx_clients_assigned_to` (`assigned_to`),
    INDEX `idx_clients_created_at` (`created_at`),
    INDEX `idx_clients_city` (`city`),
    INDEX `idx_clients_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
