CREATE TABLE IF NOT EXISTS `rate_limits` (
    `key` VARCHAR(191) NOT NULL PRIMARY KEY,
    `hits` INT UNSIGNED NOT NULL DEFAULT 1,
    `reset_at` DATETIME NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX `idx_rate_limits_reset_at` (`reset_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
